name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build & push to Docker
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: ghcr.io/dokioco/docker-elasticsearch:6